mh_stripe.settings:
  type: config_object
  label: 'MakeHaven Stripe settings'
  mapping:
    api_key_source:
      type: string
      label: 'API key source'
    api_key:
      type: string
      label: 'API key (secret)'
    portal_configuration_id:
      type: string
      label: 'Portal Configuration ID'
    show_member_portal_link:
      type: boolean
      label: 'Show member portal link'
    show_staff_customer_link:
      type: boolean
      label: 'Show staff customer link'
